name: devteamer
services:

  postgres:
    image: postgres:16-alpine
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./frontend/.env
    restart: unless-stopped
volumes:
  postgres-data:
  redis_data: